
language: rust
sudo: required
dist: trusty
rust:
  - nightly
cache: cargo
addons:
  postgresql: '9.4'
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - psql -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres
  - cargo install diesel_cli
  - diesel setup --database-url='postgres://localhost/postgres'
  - DATABASE_URL='postgres://localhost/postgres' diesel migration redo
env:
  matrix:
    - BACKEND=postgres
      DATABASE_URI=postgresql://127.0.0.1:5432/postgres
branches:
  only:
    - master