[package]
authors = ["Peter A. Tariche <ptariche@gmail.com>"]
name = "api_example"
version = "0.1.0"

[dependencies]
hyper = "0.9.10"
rustc-serialize = "0.3"
chrono = { version = "0.2", features = ["rustc-serialize"] }

[dependencies.nickel]
git = "https://github.com/nickel-org/nickel.rs.git"
